def rotatePart(partName:str, axis:str, degree:float, time:float=1): ...
def cyclicMovement(jointName:str, axis:str, amplitude:float, speed:float, phase:float, offset:float=0): ...
def reset(): ...
def openHand(side:str): ...
def closeHand(side:str): ...
def wait(time:float=1): ...
def speak(text:str, pitch:float=0.5, speed:float=0.5): ...