from definitions import *

speak("You want me to grab that?", speed=1, pitch=0.3)
rotatePart("jaw", "x", 10)
wait()
reset()
wait()
rotatePart("ShoulderL", "x", -90)
rotatePart("upperArmL", "y", 20)
rotatePart("upperArmL", "z", -20)
rotatePart("forearmL", "z", -100)
rotatePart("handL", "x", 180)
openHand("l")
wait()
closeHand("l")
speak("There you go.", speed=1, pitch=0.3)
rotatePart("jaw", "x", 10)
wait(0.5)
reset()